### ISSUE TITLE
retrieve genome-level fasta files for every organism (or subset) available in EuPathDB at once

### ISSUE THREAD

**Issue by janstrauss1** [kathryncrouch/misc#1]
Dear @kathryncrouch,

thanks for this useful script!

It would be nice to allow to retrieve genome-level fasta files for every organism and/or selected organisms available in [EuPathDB](https://eupathdb.org/eupathdb/) (e.g. AmoebaDB, CryptoDB, FungiDB...) at once.

Thanks,
Jan

**Comment by kathryncrouch** [comment]
It is not possible to do this through the portal as it is currently implemented, and in any case, the portal does not contain data files for all of our projects.  It is therefore more flexible to poll the individual project sites.  I will revisit this when the updates to the portal that we are currently working on go live.

In the meantime, I will implement the facility to download from more than one project if a list is supplied.
