### ISSUE TITLE
Combine downloaded sequences into a single fasta file

### ISSUE THREAD

**Issue by janstrauss1** [kathryncrouch/misc#2]
Dear @kathryncrouch,

It would be nice to be able to directly combine downloaded sequences from an [EuPathDB](https://eupathdb.org/eupathdb/) project into a single fasta file.

Thanks,
Jan

**Comment by kathryncrouch** [comment]
It is easy to combine downloaded fasta files into one with a single command.  However, it is much harder to deconvolute a combined file into it's component parts.  Therefore, in the interest of flexibility, I will not implement this change.

If your downloaded fasta files are all in the same directory, you can concatenate them like this:
`cat *.fasta > concatenated.fasta`
